import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createTestDB} from './helpers/d1-memory.mjs';
import {hashToken} from '../server/auth-session.js';
import {dailyQuiz,points,kstDate} from '../server/daily-quiz.js';

const origin='https://local.example';
function request(path,{cookie,method='GET',data}={}){return new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(['GET','HEAD'].includes(method)?{}:{body:JSON.stringify(data??{})})});}
async function call(handler,db,options={}){const response=await handler({request:request(options.path||'/api/daily-quiz',options),env:{DB:db}});return{status:response.status,data:await response.json()};}
async function fixture(t){const db=createTestDB();t.after(()=>db.close());for(const name of ['0012_quiz_points.sql','0013_quiz_metadata.sql'])db.sqlite.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const users=[];for(const name of ['correct','wrong']){const id=crypto.randomUUID(),token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');db.sqlite.prepare('INSERT INTO users (id,email,password_hash,name,company_name,department_name,position) VALUES (?,?,?,?,?,?,?)').run(id,`${name}@test.local`,'x',name,'c','d','p');db.sqlite.prepare('INSERT INTO sessions (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').run(crypto.randomUUID(),id,await hashToken(token),new Date(Date.now()+3600000).toISOString());users.push({id,cookie:`hsso_session=${token}`});}const quizId=crypto.randomUUID();db.sqlite.prepare('INSERT INTO daily_quizzes (id,quiz_date,question,option_a,option_b,option_c,option_d,correct_option,explanation,is_active,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(quizId,kstDate(),'안전모를 착용해야 하는 경우는?', '작업장 위험구역','퇴근 후','휴게실','식당','A','위험구역에서는 지정된 보호구를 착용해야 합니다.',1,new Date().toISOString());return{db,quizId,correct:users[0],wrong:users[1]};}

test('legacy quiz without metadata remains compatible and hides answer',async t=>{const f=await fixture(t),result=await call(dailyQuiz,f.db);assert.equal(result.status,200);assert.equal(result.data.quiz.id,f.quizId);assert.equal(result.data.quiz.category,'');assert.equal(result.data.quiz.difficulty,'');assert.deepEqual(Object.keys(result.data.quiz.options),['A','B','C','D']);assert.equal(JSON.stringify(result.data).includes('correctOption'),false);assert.equal(JSON.stringify(result.data).includes('위험구역에서는'),false);});
test('quiz metadata is returned without exposing the answer',async t=>{const f=await fixture(t);f.db.sqlite.prepare("UPDATE daily_quizzes SET category='산업안전',difficulty='중급' WHERE id=?").run(f.quizId);const result=await call(dailyQuiz,f.db);assert.equal(result.data.quiz.category,'산업안전');assert.equal(result.data.quiz.difficulty,'중급');assert.equal(JSON.stringify(result.data).includes('correctOption'),false);});
test('anonymous submission is denied',async t=>{const f=await fixture(t);assert.equal((await call(dailyQuiz,f.db,{method:'POST',data:{quizId:f.quizId,selectedOption:'A'}})).status,401);});
test('correct answer creates one attempt and +10 ledger entry',async t=>{const f=await fixture(t),result=await call(dailyQuiz,f.db,{cookie:f.correct.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'A'}});assert.equal(result.status,200);assert.equal(result.data.result.isCorrect,true);assert.equal(result.data.result.pointsAwarded,10);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM quiz_attempts').get().n,1);assert.equal(f.db.sqlite.prepare('SELECT amount FROM point_ledger').get().amount,10);});
test('wrong answer records completion and awards no points',async t=>{const f=await fixture(t),result=await call(dailyQuiz,f.db,{cookie:f.wrong.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'B'}});assert.equal(result.data.result.isCorrect,false);assert.equal(result.data.result.correctOption,'A');assert.equal(result.data.result.pointsAwarded,0);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM point_ledger').get().n,0);});
test('same quiz cannot be answered or credited twice',async t=>{const f=await fixture(t),options={cookie:f.correct.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'A'}};assert.equal((await call(dailyQuiz,f.db,options)).status,200);assert.equal((await call(dailyQuiz,f.db,options)).status,409);assert.throws(()=>f.db.sqlite.prepare("INSERT INTO point_ledger VALUES (?,?,?,?,?,?,?)").run(crypto.randomUUID(),f.correct.id,10,'quiz_correct','daily_quiz',f.quizId,new Date().toISOString()),/UNIQUE/);assert.equal(f.db.sqlite.prepare('SELECT SUM(amount) total FROM point_ledger').get().total,10);});
test('concurrent correct submissions create only one credit',async t=>{const f=await fixture(t),options={cookie:f.correct.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'A'}},results=await Promise.all([call(dailyQuiz,f.db,options),call(dailyQuiz,f.db,options)]);assert.deepEqual(results.map(result=>result.status).sort(),[200,409]);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM point_ledger').get().n,1);});
test('points endpoint returns sum and recent entries',async t=>{const f=await fixture(t);await call(dailyQuiz,f.db,{cookie:f.correct.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'A'}});const result=await call(points,f.db,{cookie:f.correct.cookie,path:'/api/points'});assert.equal(result.status,200);assert.equal(result.data.total,10);assert.equal(result.data.entries.length,1);assert.equal(result.data.entries[0].reason,'quiz_correct');});
test('invalid option and unavailable quiz are rejected',async t=>{const f=await fixture(t);assert.equal((await call(dailyQuiz,f.db,{cookie:f.correct.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'E'}})).status,400);f.db.sqlite.prepare('UPDATE daily_quizzes SET is_active=0').run();assert.equal((await call(dailyQuiz,f.db,{cookie:f.correct.cookie,method:'POST',data:{quizId:f.quizId,selectedOption:'A'}})).status,409);assert.equal((await call(dailyQuiz,f.db)).data.quiz,null);});
test('KST date does not roll with UTC midnight',()=>{assert.equal(kstDate(Date.parse('2026-09-15T15:00:00.000Z')),'2026-09-16');assert.equal(kstDate(Date.parse('2026-09-16T14:59:59.999Z')),'2026-09-16');});
