import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createTestDB} from './helpers/d1-memory.mjs';
import {inquiryCollection,inquiryItem,MAX_INQUIRY_BODY_BYTES} from '../server/inquiries.js';
import {onRequest as signup} from '../functions/api/auth/signup.js';
import {onRequest as login} from '../functions/api/auth/login.js';

const origin='https://local.example';
async function fixture(t){const db=createTestDB();t.after(()=>db.close());db.sqlite.exec(readFileSync(new URL('../migrations/0005_inquiries.sql',import.meta.url),'utf8'));const users=[];for(const [index,email] of ['inquiry-a@example.com','inquiry-b@example.com'].entries()){const data={email,password:'inquiry fixture password',name:`문의자 ${index+1}`,companyName:'회사',departmentName:'부서',position:'직급'},request=()=>new Request(origin+'/api/auth',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});assert.equal((await signup({request:request(),env:{DB:db}})).status,201);const response=await login({request:request(),env:{DB:db}}),user=(await response.json()).user;users.push({id:user.id,cookie:response.headers.get('set-cookie').split(';')[0]});}return{db,a:users[0],b:users[1]};}
async function call(handler,db,{cookie,method='GET',path='/api/inquiries',params={},data,raw,requestOrigin=origin}={}){const headers={Origin:requestOrigin,'Content-Type':'application/json'};if(cookie)headers.Cookie=cookie;const init={method,headers};if(method==='POST')init.body=raw??JSON.stringify(data);const response=await handler({request:new Request(origin+path,init),env:{DB:db},params});return{status:response.status,data:await response.json()};}
const payload=extra=>({title:'서비스 문의',content:'문의 본문입니다.',...extra});
async function create(db,user,extra){const result=await call(inquiryCollection,db,{cookie:user.cookie,method:'POST',data:payload(extra)});assert.equal(result.status,201);return result.data.inquiry;}

test('inquiry endpoints require login',async t=>{const{db}=await fixture(t);assert.equal((await call(inquiryCollection,db)).status,401);assert.equal((await call(inquiryCollection,db,{method:'POST',data:payload()})).status,401);assert.equal((await call(inquiryItem,db,{params:{id:crypto.randomUUID()}})).status,401);});
test('authenticated user creates an inquiry and spoofed owner is ignored',async t=>{const{db,a,b}=await fixture(t);const inquiry=await create(db,a,{author_user_id:b.id,authorUserId:b.id,status:'answered'});const row=db.sqlite.prepare('SELECT author_user_id,status FROM inquiry_posts WHERE id=?').get(inquiry.id);assert.equal(row.author_user_id,a.id);assert.equal(row.status,'waiting');const insert=db.calls.findLast(entry=>entry.sql.startsWith('INSERT INTO inquiry_posts'));assert(insert.args.includes(a.id));});
test('inquiry list is isolated to the signed-in owner',async t=>{const{db,a,b}=await fixture(t);await create(db,a,{title:'A 문의'});await create(db,b,{title:'B 문의'});const own=await call(inquiryCollection,db,{cookie:a.cookie});assert.equal(own.data.total,1);assert.equal(own.data.inquiries[0].title,'A 문의');assert.equal(Object.hasOwn(own.data.inquiries[0],'authorUserId'),false);});
test('only the owner can retrieve inquiry detail',async t=>{const{db,a,b}=await fixture(t),inquiry=await create(db,a);const own=await call(inquiryItem,db,{cookie:a.cookie,path:'/api/inquiries/'+inquiry.id,params:{id:inquiry.id}}),other=await call(inquiryItem,db,{cookie:b.cookie,path:'/api/inquiries/'+inquiry.id,params:{id:inquiry.id}});assert.equal(own.status,200);assert.equal(own.data.inquiry.content,'문의 본문입니다.');assert.equal(other.status,404);});
test('inquiry validation, body limit, Origin and bound values are enforced',async t=>{const{db,a}=await fixture(t);for(const data of [payload({title:''}),payload({title:'x'.repeat(201)}),payload({content:''}),payload({content:'x'.repeat(10001)})])assert.equal((await call(inquiryCollection,db,{cookie:a.cookie,method:'POST',data})).status,400);assert.equal((await call(inquiryCollection,db,{cookie:a.cookie,method:'POST',raw:'x'.repeat(MAX_INQUIRY_BODY_BYTES+1)})).status,413);assert.equal((await call(inquiryCollection,db,{cookie:a.cookie,method:'POST',data:payload(),requestOrigin:'https://evil.example'})).status,403);const title="' OR 1=1 --";await create(db,a,{title});const insert=db.calls.findLast(entry=>entry.sql.startsWith('INSERT INTO inquiry_posts'));assert(insert.args.includes(title));});
test('official work-site links open safely in a new tab',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');for(const url of ['https://www.law.go.kr/법령/산업안전보건법','https://www.law.go.kr/법령/중대재해처벌등에관한법률','https://www.moel.go.kr/','https://www.kosha.or.kr/','https://labor.moel.go.kr/minwonApply/minwonForm.do?searchVal=AH038&amp;searchGubun=1&amp;searchRIm=2']){const start=html.indexOf(`href="${url}"`);assert.notEqual(start,-1);const tag=html.slice(start,html.indexOf('>',start));assert.match(tag,/target="_blank"/);assert.match(tag,/rel="noopener noreferrer"/);}});
