import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fixture, call } from './helpers/risk-fixture.mjs';
import { hashToken } from '../server/auth-session.js';
import { assessmentItemCollection, assessmentItem } from '../server/risk-assessment-items.js';
import { adminImprovementCollection, myImprovementCollection, improvementItem, improvementPhotos, improvementPhoto, submitImprovement, reviewImprovement, MAX_IMPROVEMENT_PHOTO_BYTES } from '../server/risk-improvements.js';

const origin='https://local.example';
const apply=(db,name)=>db.sqlite.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));
class Bucket{constructor(){this.objects=new Map();this.deleted=[];this.failPut=false;}async put(key,value){if(this.failPut)throw new Error('put');this.objects.set(key,new Uint8Array(value));}async get(key){const body=this.objects.get(key);return body?{body}:null;}async delete(key){this.deleted.push(key);this.objects.delete(key);}}
async function addUser(db,email){const id=crypto.randomUUID(),token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');db.sqlite.prepare('INSERT INTO users (id,email,password_hash,name,company_name,department_name,position) VALUES (?,?,?,?,?,?,?)').run(id,email,'unused',email,'회사','부서','담당자');db.sqlite.prepare('INSERT INTO sessions (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').run(crypto.randomUUID(),id,await hashToken(token),new Date(Date.now()+3600000).toISOString());return{id,cookie:`hsso_session=${token}`};}
async function invoke(handler,f,{user=f.admin,method='GET',path='/',params={},data,form,bucket=f.bucket,db=f.db}={}){const headers={Origin:origin,Cookie:user.cookie},init={method,headers};if(data!==undefined){headers['Content-Type']='application/json';init.body=JSON.stringify(data);}if(form)init.body=form;const response=await handler({request:new Request(origin+path,init),env:{DB:db,MSDS_BUCKET:bucket},params});const copy=response.clone(),type=response.headers.get('content-type')||'';return{status:response.status,response,data:type.includes('json')?await copy.json():await copy.arrayBuffer()};}
const itemData=departmentId=>({sourceResponseId:null,departmentId,workProcess:'보일러실 점검',hazardFactor:'미끄러짐',hazardSituation:'바닥 물기로 넘어짐',currentMeasures:'정기 청소',likelihood:4,severity:3,riskScore:999,reductionMeasures:'누수 보수 및 미끄럼 방지'});
async function setup(t){const base=await fixture(t);for(const name of ['0010_company_workspaces.sql','0017_risk_response_reviews.sql','0018_risk_assessment_items.sql','0019_risk_improvements.sql'])apply(base.db,name);const otherDept=await addUser(base.db,'other-dept@example.com'),outsider=await addUser(base.db,'outsider@example.com');const company=crypto.randomUUID(),otherCompany=crypto.randomUUID(),dept=crypto.randomUUID(),dept2=crypto.randomUUID(),deptOther=crypto.randomUUID(),stamp=new Date().toISOString();for(const [id,name,admin]of[[company,'본사',base.a.id],[otherCompany,'타사',outsider.id]])base.db.sqlite.prepare('INSERT INTO companies VALUES (?,?,?,?,?,?,?)').run(id,name,name,'active',admin,stamp,stamp);for(const [id,cid,name,creator]of[[dept,company,'시설팀',base.a.id],[dept2,company,'생산팀',base.a.id],[deptOther,otherCompany,'타부서',outsider.id]])base.db.sqlite.prepare('INSERT INTO company_departments VALUES (?,?,?,?,?,?,?,?)').run(id,cid,name,name,'active',creator,stamp,stamp);for(const [user,cid,role,did]of[[base.a.id,company,'company_admin',dept],[base.b.id,company,'member',dept],[otherDept.id,company,'member',dept2],[outsider.id,otherCompany,'company_admin',deptOther]])base.db.sqlite.prepare('INSERT INTO company_memberships VALUES (?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),cid,user,role,'active',did,'',stamp,stamp);const f={...base,admin:base.a,worker:base.b,otherDept,outsider,company,otherCompany,dept,dept2,bucket:new Bucket()};const created=await invoke(assessmentItemCollection,f,{method:'POST',path:`/api/companies/${company}/risk-assessment-items`,params:{companyId:company},data:itemData(dept)});assert.equal(created.status,201);f.item=created.data.item;return f;}
async function createRequest(f){return invoke(adminImprovementCollection,f,{method:'POST',path:`/api/companies/${f.company}/risk-improvements`,params:{companyId:f.company},data:{riskAssessmentItemId:f.item.id,departmentId:f.dept,requestText:'누수 보수 후 사진을 제출해주세요.',dueDate:'2099-12-31'}});}
function photoForm(kind='BEFORE',type='image/png',bytes=new Uint8Array([137,80,78,71,13,10,26,10,1])){const form=new FormData();form.append('kind',kind);form.append('file',new Blob([bytes],{type}),'photo.png');return form;}

test('admin creates one request; member creation and duplicate are blocked',async t=>{const f=await setup(t),created=await createRequest(f);assert.equal(created.status,201);assert.equal(created.data.request.status,'REQUESTED');assert.equal((await createRequest(f)).data.error,'IMPROVEMENT_ALREADY_EXISTS');assert.equal((await invoke(adminImprovementCollection,f,{user:f.worker,method:'POST',params:{companyId:f.company},data:{riskAssessmentItemId:f.item.id,departmentId:f.dept,requestText:'요청',dueDate:'2099-12-31'}})).status,403);const event=f.db.sqlite.prepare('SELECT event_type,note,actor_user_id FROM risk_improvement_events').get();assert.deepEqual({...event},{event_type:'REQUESTED',note:'누수 보수 후 사진을 제출해주세요.',actor_user_id:f.admin.id});});

test('admin list filters by exact department, state and overdue flag',async t=>{const f=await setup(t);await createRequest(f);assert.equal((await invoke(adminImprovementCollection,f,{params:{companyId:f.company},path:`/?departmentId=${f.dept}&status=REQUESTED`})).data.requests.length,1);assert.equal((await invoke(adminImprovementCollection,f,{params:{companyId:f.company},path:`/?departmentId=${f.dept2}`})).data.requests.length,0);assert.equal((await invoke(adminImprovementCollection,f,{params:{companyId:f.company},path:'/?overdue=1'})).data.requests.length,0);});

test('department and company IDOR boundaries apply to request and photo access',async t=>{const f=await setup(t),created=await createRequest(f),id=created.data.request.id;assert.equal((await invoke(myImprovementCollection,f,{user:f.worker})).data.requests.length,1);assert.equal((await invoke(myImprovementCollection,f,{user:f.otherDept})).data.requests.length,0);assert.equal((await invoke(improvementItem,f,{user:f.otherDept,params:{requestId:id}})).status,404);assert.equal((await invoke(improvementItem,f,{user:f.outsider,params:{requestId:id}})).status,404);const uploaded=await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm()});assert.equal(uploaded.status,201);assert.equal((await invoke(improvementPhoto,f,{user:f.otherDept,params:{requestId:id,photoId:uploaded.data.photo.id}})).status,404);assert.equal((await invoke(improvementPhoto,f,{user:f.outsider,params:{requestId:id,photoId:uploaded.data.photo.id}})).status,404);});

test('action, photos, submit, revision, resubmit and approval preserve history and calculate risk',async t=>{const f=await setup(t),created=await createRequest(f),id=created.data.request.id;assert.equal((await invoke(improvementItem,f,{user:f.worker,method:'PATCH',params:{requestId:id},data:{actionText:'누수 배관을 교체하고 미끄럼 방지 매트를 설치함'}})).status,200);const before=await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm('BEFORE')});const after=await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm('AFTER')});assert.equal(before.status,201);assert.equal(after.status,201);assert.equal((await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm('BEFORE','text/plain',new TextEncoder().encode('bad'))})).status,400);assert.equal((await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm('BEFORE','image/png',new Uint8Array(MAX_IMPROVEMENT_PHOTO_BYTES+1))})).status,413);
assert.equal((await invoke(reviewImprovement,f,{method:'POST',params:{companyId:f.company,requestId:id},data:{action:'APPROVED',afterLikelihood:2,afterSeverity:3,afterRiskScore:999}})).status,409);assert.equal((await invoke(submitImprovement,f,{user:f.worker,method:'POST',params:{requestId:id},data:{}})).status,200);assert.equal((await invoke(improvementItem,f,{user:f.worker,method:'PATCH',params:{requestId:id},data:{actionText:'변조'}})).status,409);assert.equal((await invoke(submitImprovement,f,{user:f.worker,method:'POST',params:{requestId:id},data:{}})).status,409);
const revision=await invoke(reviewImprovement,f,{method:'POST',params:{companyId:f.company,requestId:id},data:{action:'REVISION_REQUIRED',reason:'개선 후 사진을 더 명확히 첨부해주세요.'}});assert.equal(revision.status,200);assert.equal((await invoke(improvementItem,f,{user:f.worker,method:'PATCH',params:{requestId:id},data:{actionText:'사진을 재촬영하고 조치내용을 보완함'}})).status,200);assert.equal((await invoke(submitImprovement,f,{user:f.worker,method:'POST',params:{requestId:id},data:{}})).status,200);const approved=await invoke(reviewImprovement,f,{method:'POST',params:{companyId:f.company,requestId:id},data:{action:'APPROVED',afterLikelihood:2,afterSeverity:3,afterRiskScore:999}});assert.equal(approved.status,200);assert.equal(approved.data.afterRiskScore,6);const detail=await invoke(improvementItem,f,{user:f.worker,params:{requestId:id}});assert.equal(detail.data.request.status,'APPROVED');assert.equal(detail.data.request.afterRiskScore,6);assert.deepEqual(detail.data.request.events.map(e=>e.eventType),['REQUESTED','SUBMITTED','REVISION_REQUIRED','SUBMITTED','APPROVED']);assert.equal(detail.data.request.events[2].note,'개선 후 사진을 더 명확히 첨부해주세요.');assert.equal((await invoke(improvementItem,f,{user:f.worker,method:'PATCH',params:{requestId:id},data:{actionText:'승인 후 변경'}})).status,409);assert.equal((await invoke(improvementPhoto,f,{user:f.worker,method:'DELETE',params:{requestId:id,photoId:before.data.photo.id}})).status,409);});

test('R2 failures leave no metadata and DB failure removes the uploaded orphan',async t=>{const f=await setup(t),created=await createRequest(f),id=created.data.request.id;f.bucket.failPut=true;assert.equal((await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm()})).status,502);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) count FROM risk_improvement_photos').get().count,0);f.bucket.failPut=false;const wrapped={...f.db,prepare(sql){const statement=f.db.prepare(sql);if(!sql.startsWith('INSERT INTO risk_improvement_photos'))return statement;return{bind(...args){statement.bind(...args);return{async run(){throw new Error('db failed');}};}};}};assert.equal((await invoke(improvementPhotos,f,{user:f.worker,method:'POST',params:{requestId:id},form:photoForm(),db:wrapped})).status,500);assert.equal(f.bucket.objects.size,0);assert.equal(f.bucket.deleted.length,1);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) count FROM risk_improvement_photos').get().count,0);});

test('item exposes improvement status and cannot be deleted once a request exists',async t=>{const f=await setup(t),created=await createRequest(f);assert.equal(created.status,201);const items=await call(assessmentItemCollection,f.db,{cookie:f.admin.cookie,params:{companyId:f.company},path:`/api/companies/${f.company}/risk-assessment-items`});assert.equal(items.data.items[0].improvement.status,'REQUESTED');const deleted=await call(assessmentItem,f.db,{cookie:f.admin.cookie,method:'DELETE',params:{companyId:f.company,itemId:f.item.id}});assert.equal(deleted.status,409);assert.equal(deleted.data.error,'IMPROVEMENT_REQUEST_EXISTS');assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) count FROM risk_assessment_items WHERE id=?').get(f.item.id).count,1);});
