import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,call,createSurvey,responsePayload,publicResponses,adminResponses,adminResponseItem,responseCsv } from './helpers/risk-fixture.mjs';
import { MAX_RESPONSE_BODY_BYTES } from '../server/risk-surveys.js';

async function submit(db,survey,data=responsePayload()){return call(publicResponses,db,{method:'POST',path:`/api/public/risk-surveys/${survey.publicToken}/responses`,params:{token:survey.publicToken},data});}
test('valid response stores server-calculated scores and full JSON',async t=>{const{db,a}=await fixture(t);const survey=await createSurvey(db,a);assert.equal((await submit(db,survey,{...responsePayload(),preRiskScore:999,postRiskScore:999})).status,400);assert.equal((await submit(db,survey)).status,201);const row=db.sqlite.prepare('SELECT * FROM risk_responses').get();assert.equal(row.pre_risk_score,20);assert.equal(row.post_risk_score,4);assert.equal(JSON.parse(row.response_data).preRiskScore,20);});
test('rating bounds and yes/no branches are validated',async t=>{const{db,a}=await fixture(t);const survey=await createSurvey(db,a);for(const data of [{...responsePayload(),preLikelihood:6},{...responsePayload(),preSeverity:0},{...responsePayload(),hasHazard:false,safeReason:'',preLikelihood:null,preSeverity:null,postLikelihood:null,postSeverity:null}])assert.equal((await submit(db,survey,data)).status,400);const safe={...responsePayload(),hasHazard:false,hazardTypes:[],hazardDescription:'',location:'',improvementSuggestion:'',preLikelihood:null,preSeverity:null,postLikelihood:null,postSeverity:null,safeReason:'절차 준수'};assert.equal((await submit(db,survey,safe)).status,201);});
test('anonymous response removes personal data and employee duplicate policy is scoped to survey',async t=>{const{db,a}=await fixture(t);const survey=await createSurvey(db,a);const anonymous={...responsePayload(),respondentName:'비밀',department:'비밀',employeeId:'비밀',isAnonymous:true};assert.equal((await submit(db,survey,anonymous)).status,201);const row={...db.sqlite.prepare('SELECT respondent_name,department,employee_id,is_anonymous FROM risk_responses').get()};assert.deepEqual(row,{respondent_name:null,department:null,employee_id:null,is_anonymous:1});assert.equal((await submit(db,survey)).status,201);assert.equal((await submit(db,survey)).status,409);const other=await createSurvey(db,a);assert.equal((await submit(db,other)).status,201);});
test('inactive, ended and oversized submissions are blocked',async t=>{const{db,a}=await fixture(t);const survey=await createSurvey(db,a);assert.equal((await call(publicResponses,db,{method:'POST',params:{token:survey.publicToken},raw:'x'.repeat(MAX_RESPONSE_BODY_BYTES+1)})).status,413);db.sqlite.prepare('UPDATE risk_surveys SET is_active=0 WHERE id=?').run(survey.id);assert.equal((await submit(db,survey)).data.error,'SURVEY_INACTIVE');db.sqlite.prepare("UPDATE risk_surveys SET is_active=1,end_date='2020-01-01' WHERE id=?").run(survey.id);assert.equal((await submit(db,survey)).data.error,'SURVEY_ENDED');});
test('only owner reads responses; pagination and survey isolation hold',async t=>{const{db,a,b}=await fixture(t);const survey=await createSurvey(db,a);await submit(db,survey);for(let i=0;i<24;i++){const p=responsePayload();p.employeeId='E'+i;await submit(db,survey,p);}const path=`/api/risk-surveys/${survey.id}/responses?limit=20&offset=0`;assert.equal((await call(adminResponses,db,{cookie:b.cookie,path,params:{id:survey.id}})).status,404);const page=await call(adminResponses,db,{cookie:a.cookie,path,params:{id:survey.id}});assert.equal(page.data.responses.length,20);assert.equal(page.data.hasMore,true);const id=page.data.responses[0].id;assert.equal((await call(adminResponseItem,db,{cookie:a.cookie,params:{id:survey.id,responseId:id}})).status,200);assert.equal((await call(adminResponseItem,db,{cookie:b.cookie,params:{id:survey.id,responseId:id}})).status,404);});
test('CSV has UTF-8 BOM, Korean headers and formula injection protection',async t=>{const{db,a}=await fixture(t);const survey=await createSurvey(db,a);const p=responsePayload();p.respondentName='=CMD()';await submit(db,survey,p);const result=await call(responseCsv,db,{cookie:a.cookie,path:`/api/risk-surveys/${survey.id}/responses.csv`,params:{id:survey.id},contentType:null});assert.equal(result.status,200);assert.deepEqual([...new Uint8Array(await result.response.arrayBuffer()).slice(0,3)],[0xEF,0xBB,0xBF]);assert.match(result.data,/제출일/);assert.match(result.data,/"'=CMD\(\)"/);assert.match(result.response.headers.get('content-disposition'),/filename\*=UTF-8/);});
