import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,call,createSurvey,surveyPayload,surveyCollection,surveyItem,publicSurvey } from './helpers/risk-fixture.mjs';
import { MAX_SURVEY_BODY_BYTES } from '../server/risk-surveys.js';

test('survey creation requires login, ignores owner spoof, and tokens are unique',async t=>{const{db,a,b}=await fixture(t);assert.equal((await call(surveyCollection,db,{method:'POST',data:surveyPayload()})).status,401);const one=await createSurvey(db,a,{...surveyPayload(),owner_user_id:b.id});const two=await createSurvey(db,a);assert.notEqual(one.publicToken,two.publicToken);assert.equal(one.publicToken.length,64);assert.equal(db.sqlite.prepare('SELECT owner_user_id FROM risk_surveys WHERE id=?').get(one.id).owner_user_id,a.id);});
test('owner lists and reads only own surveys',async t=>{const{db,a,b}=await fixture(t);const survey=await createSurvey(db,a);await createSurvey(db,b);const own=await call(surveyCollection,db,{cookie:a.cookie});assert.equal(own.data.surveys.length,1);assert.equal(own.data.summary.total,1);assert.equal((await call(surveyItem,db,{cookie:b.cookie,path:'/api/risk-surveys/'+survey.id,params:{id:survey.id}})).status,404);});
test('active toggle requires same origin and owner',async t=>{const{db,a,b}=await fixture(t);const survey=await createSurvey(db,a);assert.equal((await call(surveyItem,db,{cookie:b.cookie,method:'PATCH',path:'/api/risk-surveys/'+survey.id,params:{id:survey.id},data:{isActive:false}})).status,404);assert.equal((await call(surveyItem,db,{cookie:a.cookie,method:'PATCH',path:'/api/risk-surveys/'+survey.id,params:{id:survey.id},data:{isActive:false},requestOrigin:'https://evil.example'})).status,403);const changed=await call(surveyItem,db,{cookie:a.cookie,method:'PATCH',path:'/api/risk-surveys/'+survey.id,params:{id:survey.id},data:{isActive:false}});assert.equal(changed.status,200);assert.equal(changed.data.survey.status,'inactive');});
test('invalid dates, JSON, oversized body and Origin fail safely',async t=>{const{db,a}=await fixture(t);for(const dates of [{startDate:'2030-02-01',endDate:'2030-01-01'},{startDate:'2030-02-31',endDate:'2030-03-01'}])assert.equal((await call(surveyCollection,db,{cookie:a.cookie,method:'POST',data:{...surveyPayload(),...dates}})).status,400);assert.equal((await call(surveyCollection,db,{cookie:a.cookie,method:'POST',raw:'{'})).status,400);assert.equal((await call(surveyCollection,db,{cookie:a.cookie,method:'POST',raw:'x'.repeat(MAX_SURVEY_BODY_BYTES+1)})).status,413);assert.equal((await call(surveyCollection,db,{cookie:a.cookie,method:'POST',data:surveyPayload(),requestOrigin:'https://evil.example'})).status,403);});
test('public lookup exposes no owner data and handles missing/inactive/date windows',async t=>{const{db,a}=await fixture(t);const survey=await createSurvey(db,a);const get=()=>call(publicSurvey,db,{path:'/api/public/risk-surveys/'+survey.publicToken,params:{token:survey.publicToken}});const live=await get();assert.equal(live.status,200);assert.equal(JSON.stringify(live.data).includes(a.id),false);assert.equal(Object.hasOwn(live.data.survey,'publicToken'),false);assert.equal((await call(publicSurvey,db,{params:{token:'0'.repeat(64)}})).status,404);db.sqlite.prepare('UPDATE risk_surveys SET is_active=0 WHERE id=?').run(survey.id);assert.equal((await get()).data.error,'SURVEY_INACTIVE');db.sqlite.prepare("UPDATE risk_surveys SET is_active=1,start_date='2099-01-01' WHERE id=?").run(survey.id);assert.equal((await get()).data.error,'SURVEY_NOT_STARTED');db.sqlite.prepare("UPDATE risk_surveys SET start_date='2020-01-01',end_date='2020-01-02' WHERE id=?").run(survey.id);assert.equal((await get()).data.error,'SURVEY_ENDED');});
